login_route:
    path:     /login
    defaults: { _controller: security_controller:loginAction }

user_registration:
    path:     /register
    defaults: { _controller: security_controller:registerAction }

homepage:
    path:     /
    methods:  [ GET ]
    defaults: { _controller: product_controller:indexAction }

products_filter:
    path:     /products/filter
    methods:  [ GET ]
    defaults: { _controller: product_controller:filterAction }

product:
    path:     /products/{id}
    methods:  [ GET ]
    defaults: { _controller: product_controller:viewAction }

products:
    path:     /products
    methods:  [ GET ]
    defaults: { _controller: product_controller:indexAction }

cart:
    path:     /cart
    methods:  [ GET, POST ]
    defaults: { _controller: cart_controller:indexAction }

add_product:
    path:     /cart/product
    methods:  [ POST ]
    defaults: { _controller: cart_controller:addProductAction }

remove_product:
    path:     /cart/product/{id}
    methods:  [ DELETE ]
    defaults: { _controller: cart_controller:removeProductAction }

order:
    path:     /orders/{id}
    defaults: { _controller: order_controller:viewAction }