login_route:
    path:     /login
    defaults: { _controller: security_controller:loginAction }

user_registration:
    path:     /register
    defaults: { _controller: security_controller:registerAction }
